### ISSUE TITLE
pastDisplayNames break if non-empty

### ISSUE THREAD

**Issue by blubbll** [vrchatapi/vrchatapi-csharp#1]
Had to do a shitty quickfix to make the lib non break.

c = Regex.Replace(response.Content, "\"pastDisplayNames\":\\[.*]", "\"pastDisplayNames\":[]");

**Comment by Foorack** [comment]
The problem was that pastDisplayNames was a "array of strings" rather than "array of objects" in the spec. This has been fixed in 1.1.2 and the C# library has been upgraded to this version.
