### ISSUE TITLE
APIs never auth

### ISSUE THREAD

**Issue by ChronicallyKyra** [vrchatapi/vrchatapi-csharp#12]
After trying various things, from using 2FA providers to making a new vrc account to straight up pasting in the code on the readme, I can never get the API to auth.

In trying to auth before calling a UsersApi method, I always get `No API Key provided!` with code 401, as seen here:

```csharp
// .NET 7.0.102

Configuration vrcConfig = new Configuration();
vrcConfig.Username = vrcLogin.Username;
vrcConfig.Password = vrcLogin.Password;
vrcConfig.AddApiKey("apiKey", vrcLogin.ApiKey);
vrcConfig.Timeout = 5000;

AuthenticationApi auth = new AuthenticationApi(vrcConfig);
CurrentUser user = auth.GetCurrentUser(); // user properties are all null

...

UsersApi api = new UsersApi(vrcApiConfig);
            User vrcUser;
            try {
                vrcUser = await api.GetUserAsync(vrcId);
            } catch (ApiException e) {
                await ctx.EditResponseAsync(new DiscordWebhookBuilder().WithContent("Idk man, something went wrong.. ?"));
                await Console.Error.WriteLineAsync(e.Message); // Error calling GetUser: {"error":{"message":"\"No API Key provided!\"","status_code":401}}
                return;
            }
```

I've looked through all of the docs that I could find, and I'm sure that the apiKey, username, and password are all correct.  I really hope I'm just dumb and am missing something, but I don't know what it'd be.  Thank you to anyone who looks into the issue

**Comment by ariesclark** [comment]
Hi, VRChat no longer throws the missing API error.
