### ISSUE TITLE
GetWorldInstanceWithHttpInfoAsync fails with group instance id's; due to encoding.

### ISSUE THREAD

**Issue by MistressPlague** [vrchatapi/vrchatapi-csharp#16]
Due to the ~'s in the URL that vrc api depends on, it fails completely as they get blindly encoded.

**Comment by ariesclark** [comment]
Can you demonstrate which URLs and what errors you encounter?

**Comment by MistressPlague** [comment]
So, I solved it. In apiclient, PathParameters needs the encode argument set to false. VRCApi always receives them non-encoded.

**Comment by MistressPlague** [comment]
https://github.com/vrchatapi/vrchatapi-csharp/blob/b94dfcfe7d6f5591ef93aca5bc04813793914204/src/VRChat.API/Client/ApiClient.cs#L295 needs , false at the end of the args.

**Comment by jellejurre** [comment]
Fixed when #23 was merged
