### ISSUE TITLE
Cannot Login with AddApiKey (return 401 error)

### ISSUE THREAD

**Issue by ogatomo83** [vrchatapi/vrchatapi-csharp#22]
What I want to do.

I am using WPF to create a desktop app.
Want to keep the app logged in after it is restarted.

However, when I set up auth using AddApiKey, it returns an error like the one shown in the attached image, and I am redirected to the login page.

This is part of the code I wrote.
```
Configuration config = new Configuration
{
    BasePath = "https://vrchat.com/api/1",
    UserAgent = "VRChatAPI/1.0",
};

config.AddApiKey("auth", "authcookie_xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx");
config.AddApiKeyPrefix("auth", "Bearer");
config.AddApiKey("twoFactorAuth", "xxxxxxxxxxxxxxxxxxxxxxxxx.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx");

authApi = new AuthenticationApi(config);

try
{
    // トークンが有効か確認
    var currentUser = authApi.GetCurrentUser();
    if (currentUser != null)
    {
        // 認証成功、アプリケーションを通常通り続行
        MessageBox.Show($"Logged in as {currentUser.DisplayName}");
        return;
    }
}
catch (Exception ex)
{
    MessageBox.Show("Authentication check failed: " + ex.Message);
    Console.WriteLine("Authentication check failed: " + ex.Message);
}
```
this is a error(ex.Message).
![image](https://github.com/user-attachments/assets/e82e8afd-6c95-4ee4-8494-09114b699d02)

Environment:
Windows 11
Visual Studio 2022
net8.0

**Comment by jellejurre** [comment]
I believe that this issue is already fixed on main but is not released yet

Could you try building the dll from main and using that?

**Comment by jellejurre** [comment]
With the code from main, this works:
https://github.com/vrchatapi/vrchatapi-csharp/pull/20#issuecomment-2278460593

**Comment by ogatomo83** [comment]
Thank you!
It's done.
