### ISSUE TITLE
Cookie Storage issue ("missing credentials")

### ISSUE THREAD

**Issue by petrspelos** [vrchatapi/vrchatapi-csharp#5]
## Summary

Cookies don't seem to be stored after calling `GetCurrentUserAsync`.

## My findings

I was able to resolve this in my fork by adding cookies from the API result directly into `CookieContainer` instead of `result.Cookies` since they don't seem to end up in the container otherwise.

## Affected places

https://github.com/vrchatapi/vrchatapi-csharp/blob/bb8bb09a9b24d30cf4f8cd1a513b3d473176af6c/src/VRChat.API/Client/ApiClient.cs#L660

and

https://github.com/vrchatapi/vrchatapi-csharp/blob/bb8bb09a9b24d30cf4f8cd1a513b3d473176af6c/src/VRChat.API/Client/ApiClient.cs#L546

## Additional Info

Since you guys know your system a little better, feel free to verify what's going on.
I'd PR the change, but then again, it's more of a quick-fix at my end rather than an actual patch.

This was quite a headache to find... 😅 At least things are working for me now.

**Comment by Foorack** [comment]
Thank you @petrspelos , this should now be fixed. Please try `1.6.4-rc1` if you have time.

**Comment by petrspelos** [comment]
Yeah, @Foorack, that resolved our issue. Thanks ☺️
