### ISSUE TITLE
SystemApi.GetInfoPush "missing credentials" error

### ISSUE THREAD

**Issue by EpsiRho** [vrchatapi/vrchatapi-csharp#6]
Even when already authenticated, GetInfoPush returns:
```
{\"error\":{\"message\":\"\\\"Missing Credentials\\\"\",\"status_code\":401}}
```

**Comment by ariesclark** [comment]
Is this issue still persistent?

**Comment by SGA-max-faxalv** [comment]
@EpsiRho If you are having issues, try url-encode your username and password if they contain non-ascii characters.

**Comment by jellejurre** [comment]
Tested, works now
